### ISSUE TITLE
Port Chrome "Web Extension" addon to Firefox

### ISSUE THREAD

**Issue by strigona-worksight** [Athou/commafeed-firefox#6]
Firefox 57 is the first Web Extension only release. I checked the Chrome addon and it appears to be compatible for a direct port to Firefox.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

I would fork & release it, but the source code is not licensed and so it wouldn't be right.

**Comment by strigona-worksight** [comment]
FYI: https://addons.mozilla.org/en-US/firefox/addon/commafeed_we/

No code changes required, just published the Chrome extension on AMO.

**Comment by Athou** [comment]
I updated the addon https://addons.mozilla.org/en-US/firefox/addon/commafeed/ earlier today.
I needed to make some changes to the manifest in order to have the options working.

**Comment by strigona-worksight** [comment]
Oh right.. I completely forgot about the options :) the counter was working for me, so I was happy.
